name: moso
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ed25519_hd_key: ^2.2.0
  cupertino_icons: ^1.0.2
  web3dart: ^2.7.0
  flutter_dotenv: ^5.1.0
  bip39: ^1.0.6
  hex: ^0.2.0
  shared_preferences: ^2.2.0
  dio: ^5.3.0
  provider: ^6.0.5
  floor: ^1.4.2
  flutter_bloc: ^8.1.3
  intl: ^0.18.1
  get_it: ^7.6.0
  retrofit: ^4.0.1
  flutter_hooks: ^0.20.0
  injectable: ^2.1.2
  go_router: ^10.0.0
  jiffy: ^6.2.1
  cached_network_image: ^3.2.3
  google_fonts: ^5.1.0
  equatable: ^2.0.5
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  floor_generator: ^1.4.2
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1
  injectable_generator: ^2.1.6


flutter:

  uses-material-design: true

        
    
    
                                      